Repository albertcastaned/Earth2099, pull requests merged in 2020-11, with the labels that each got.

#58 fix: set static region for cross play
  .github/workflows/deploy.yml
  Mango/Assets/ColorSkies/Skies/Sky_5.mat
  Mango/Assets/Scripts/GameLobby.cs
Labels: area:network, enhancement

#67 feat: Add chatting and notifications box to game
  Mango/Assets/ColorSkies/Skies/Sky_5.mat
  Mango/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Mango/Assets/Plugins/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Outline.mat
  Mango/Assets/Resources/Chat.prefab
  Mango/Assets/Resources/Chat.prefab.meta
  Mango/Assets/Resources/Message.prefab
  Mango/Assets/Resources/Message.prefab.meta
  Mango/Assets/Resources/Player.prefab
  Mango/Assets/Scripts/CameraFollow.cs
  Mango/Assets/Scripts/Player.cs
  Mango/Assets/Scripts/RoomController.cs
  Mango/Assets/Scripts/UI/ChatManager.cs
  Mango/Assets/Scripts/UI/ChatManager.cs.meta
  Mango/Assets/Scripts/UI/FPSCounter.cs
  Mango/Assets/Scripts/UI/FPSCounter.cs.meta
  Mango/Assets/Scripts/UI/MessageDialog.cs
Labels: area:frontend, area:network

#73 feat: Graphical settings
  Mango/Assets/Fonts.meta
  Mango/Assets/Fonts/Zekton.ttf
  Mango/Assets/Fonts/Zekton.ttf.meta
  Mango/Assets/Images/Circle.mat
  Mango/Assets/Images/background_bar.png.meta
  Mango/Assets/PartyHealth.cs
  Mango/Assets/PartyHealth.cs.meta
  Mango/Assets/Plugins/ColorSkies/Skies/Sky_5.mat
  Mango/Assets/Plugins/Mapbox/Resources/Mapbox/PrefabScreens/CitySimulator.gif
  Mango/Assets/Plugins/Mapbox/Resources/Mapbox/PrefabScreens/CitySimulator.gif.meta
  Mango/Assets/Plugins/Mapbox/Resources/Mapbox/PrefabScreens/Location-basedGame.gif
  Mango/Assets/Plugins/Mapbox/Resources/Mapbox/PrefabScreens/Location-basedGame.gif.meta
  Mango/Assets/Plugins/Mapbox/Resources/Mapbox/PrefabScreens/TabletopAR.gif
  Mango/Assets/Plugins/Mapbox/Resources/Mapbox/PrefabScreens/TabletopAR.gif.meta
  Mango/Assets/Plugins/Mapbox/Resources/Mapbox/PrefabScreens/WorldScaleAR.gif
  Mango/Assets/Plugins/Mapbox/Resources/Mapbox/PrefabScreens/WorldScaleAR.gif.meta
  Mango/Assets/Plugins/Mapbox/Resources/Mapbox/PrefabScreens/placeholder.png
  Mango/Assets/Plugins/Mapbox/Resources/Mapbox/PrefabScreens/placeholder.png.meta
  Mango/Assets/Plugins/Mapbox/Resources/MapboxStyles/Styles/MapboxSampleStyles/Realistic/Assets/Materials/RealisticSideMaterial.mat
  Mango/Assets/Plugins/Mapbox/Resources/MapboxStyles/Styles/MapboxSampleStyles/Realistic/Assets/Materials/RealisticTopMaterial.mat
  Mango/Assets/Plugins/NavMesh/NavMeshComponents/Editor/NavMeshSurfaceEditor.cs
  Mango/Assets/Plugins/NavMesh/NavMeshComponents/Scripts/NavMeshSurface.cs
  Mango/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Mango/Assets/Resources/EnemyParent.prefab
  Mango/Assets/Resources/HealthBar.prefab
  Mango/Assets/Resources/HealthBar.prefab.meta
  Mango/Assets/Resources/Orc.prefab
  Mango/Assets/Resources/Player.prefab
  Mango/Assets/Resources/Slime.prefab
  Mango/Assets/Resources/Spiny.prefab
  Mango/Assets/Scenes/DebugLevel.unity
  Mango/Assets/Scenes/DebugLevel/NavMesh-Map 1.asset
  Mango/Assets/Scenes/DebugLevel/NavMesh-Map 1.asset.meta
  Mango/Assets/Scenes/DebugLevel/NavMesh-Map 2.asset
  Mango/Assets/Scenes/DebugLevel/NavMesh-Map 2.asset.meta
  Mango/Assets/Scenes/Level.unity
  Mango/Assets/Scenes/Level/OcclusionCullingData.asset
  Mango/Assets/Scripts/Enemies/CreateEnemies.cs
  Mango/Assets/Scripts/Enemies/Enemy.cs
  Mango/Assets/Scripts/Map/BakeRuntime.cs
  Mango/Assets/Scripts/Player/Player.cs
  Mango/Assets/Scripts/System/ApplicationManager.cs
  Mango/Assets/Scripts/System/ApplicationManager.cs.meta
  Mango/Assets/Scripts/System/DebugController.cs
  Mango/Assets/Scripts/System/GameLobby.cs
  Mango/Assets/Scripts/System/RoomController.cs
  Mango/Assets/Scripts/System/Singleton.cs
  Mango/Assets/Scripts/System/Singleton.cs.meta
  Mango/Assets/SettingsMenu.cs
  Mango/Assets/SettingsMenu.cs.meta
  Mango/ProjectSettings/NavMeshAreas.asset
  Mango/ProjectSettings/TagManager.asset
Labels: area:frontend, enhancement

#76 fix(UI): Added details in scenes
  Mango/Assets/Fonts/Zekton SDF.asset
  Mango/Assets/Fonts/Zekton SDF.asset.meta
  Mango/Assets/Fonts/ZektonPRO.asset
  Mango/Assets/Fonts/ZektonPRO.asset.meta
  Mango/Assets/Images/PinClipart.com_sleepy-hollow-clip-art_2302653.png
  Mango/Assets/Images/PinClipart.com_sleepy-hollow-clip-art_2302653.png.meta
  Mango/Assets/Plugins/ColorSkies/Skies/Sky_5.mat
  Mango/Assets/Resources/EnemyParent.prefab
  Mango/Assets/Resources/LoadingCanvas.prefab
  Mango/Assets/Resources/Message.prefab
  Mango/Assets/Resources/Player.prefab
  Mango/Assets/Resources/PrefabsUI/SF Title.prefab
  Mango/Assets/Scenes/AuthMenu.unity
  Mango/Assets/Scenes/ChangeColor.unity
  Mango/Assets/Scenes/Loading.unity
  Mango/Assets/Scenes/Loading.unity.meta
  Mango/Assets/Scenes/Menu 3D.unity
  Mango/Assets/Scripts/Authentication/AuthHandler.cs
  Mango/Packages/packages-lock.json
  Mango/ProjectSettings/GraphicsSettings.asset
Labels: area:frontend, enhancement

#80 feat: max quantity of bullets
  Mango/.idea/.idea.Mango/.idea/contentModel.xml
  Mango/.idea/.idea.Mango/.idea/indexLayout.xml
  Mango/.idea/.idea.Mango/.idea/workspace.xml
  Mango/Assets/Plugins/ColorSkies/Skies/Sky_5.mat
  Mango/Assets/Resources/BlueGun.prefab
  Mango/Assets/Resources/Bullet.prefab
  Mango/Assets/Resources/EnemyParent.prefab
  Mango/Assets/Resources/Gun.prefab
  Mango/Assets/Resources/Orc.prefab
  Mango/Assets/Resources/PlasmaExplosionEffect.prefab
  Mango/Assets/Resources/Player.prefab
  Mango/Assets/Resources/Slime.prefab
  Mango/Assets/Resources/Spiny.prefab
  Mango/Assets/Scripts/Enemies/Enemy.cs
  Mango/Assets/Scripts/ProjectileGun.cs
Labels: area:weapons

#81 feat: increase score when enemy dies
  Mango/.gitignore
  Mango/.idea/.idea.Mango/.idea/codeStyles/codeStyleConfig.xml
  Mango/.idea/.idea.Mango/.idea/contentModel.xml
  Mango/.idea/.idea.Mango/.idea/encodings.xml
  Mango/.idea/.idea.Mango/.idea/indexLayout.xml
  Mango/.idea/.idea.Mango/.idea/modules.xml
  Mango/.idea/.idea.Mango/.idea/projectSettingsUpdater.xml
  Mango/.idea/.idea.Mango/.idea/vcs.xml
  Mango/.idea/.idea.Mango/.idea/workspace.xml
  Mango/.idea/.idea.Mango/riderModule.iml
  Mango/Assets/Plugins/ColorSkies/Skies/Sky_5.mat
  Mango/Assets/Plugins/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Mango/Assets/Resources/Orc.prefab
  Mango/Assets/Resources/Player.prefab
  Mango/Assets/Resources/Slime.prefab
  Mango/Assets/Resources/Spiny.prefab
  Mango/Assets/Scenes/Level.unity
  Mango/Assets/Scripts/Enemies/Enemy.cs
  Mango/Assets/Scripts/PartyHealth.cs
  Mango/Assets/Scripts/Player/Bullet.cs
  Mango/Assets/Scripts/Player/Player.cs
  Mango/Assets/Scripts/System/RoomController.cs
  Mango/Assets/Scripts/createPowerups.cs
  Mango/ProjectSettings/GraphicsSettings.asset
Labels: area:enemies, area:network
